feedName: Test Feed

defaultEntriesPerPage: 10

databaseConfiguration:
  driverClass: com.mysql.jdbc.Driver
  user: usr
  password: pwd
  url: jdbc:mysql://localhost:3306/feed_db
  validationQuery: select 1

# Local server HTTP configuration
http:
  port: 8080
  adminPort: 8081
  requestLog:
    timeZone: GB
    console:
      enabled: true

# Logging configuration
logging:
  level: INFO
  console:
    enabled: true
    timeZone: GB
